--
-- PostgreSQL database cluster dump
--

-- Started on 2026-03-16 15:14:08 CST

\restrict MiJVnDs0So2qsIXuq4VOSC6te4tlXJUCNn1vyy8beEdwCHD5z8rpfaPYCp1JWkl

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE admin;
ALTER ROLE admin WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:M44coMR45NpQIPXJpxHBsw==$cgWQmBzudKgoZ1DOq+sj5gEZweMRXr5bfPRA00SoJhk=:nrk7G9/9y4Fh6clP8nuGzt1obwVAyDiorNIzsBNse2c=';
CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:u489ltn6kOxhcuZqqROOSA==$HRKLcuvpA8pBjC4EiPfRr1AU1Lv0m1AcSKcOwrQhIHo=:wDhf2PE9Y3uL1atR2SkfGgyBiN3jww9SOOqjFp/N2NE=';
CREATE ROLE prueba;
ALTER ROLE prueba WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:O+1LniGJxQJKcUgZLdgQmQ==$oK6VpUYwQoDXZ0dBiWvZ2kNW9h0+ib9aeyLh7Rz1q4E=:XgPo046j4Ht6o4TW10LhvuWMF3RtFSjhnkNDN2gBIm4=';
CREATE ROLE root;
ALTER ROLE root WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:vouYnjXo+1McdoN0J3qCKg==$G+Y/e4NtS+PVnRBMdl2D9TY0U/2+btc3AtGuHNkDoTs=:kUkJwq65KnIIx2uZzGLY/Ucu6glZmOxC8WMoULyZEws=';

--
-- User Configurations
--








\unrestrict MiJVnDs0So2qsIXuq4VOSC6te4tlXJUCNn1vyy8beEdwCHD5z8rpfaPYCp1JWkl

--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

\restrict GtL2iTZGh6aGwjDcGwMihFa4aNkdSxaXYjrUewx1W483VgedcXWgETRrWLopv6R

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict GtL2iTZGh6aGwjDcGwMihFa4aNkdSxaXYjrUewx1W483VgedcXWgETRrWLopv6R

--
-- Database "api_db" dump
--

--
-- PostgreSQL database dump
--

\restrict VKNqCdbdJJtxEAteQP0bMHixgEetlGgHxTrcKv19tZjmguWxijfspLihuSIgFPb

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3502 (class 1262 OID 16453)
-- Name: api_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE api_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE api_db OWNER TO postgres;

\unrestrict VKNqCdbdJJtxEAteQP0bMHixgEetlGgHxTrcKv19tZjmguWxijfspLihuSIgFPb
\connect api_db
\restrict VKNqCdbdJJtxEAteQP0bMHixgEetlGgHxTrcKv19tZjmguWxijfspLihuSIgFPb

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16455)
-- Name: cake_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cake_migrations (
    id integer NOT NULL,
    version bigint NOT NULL,
    migration_name character varying(100) DEFAULT NULL::character varying,
    plugin character varying(100) DEFAULT NULL::character varying,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    breakpoint boolean DEFAULT false NOT NULL
);


ALTER TABLE public.cake_migrations OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16454)
-- Name: cake_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cake_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cake_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16476)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id integer NOT NULL,
    nombre character varying(100),
    email character varying(100),
    telefono character varying(20)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16475)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cliente_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cliente_id_seq OWNER TO postgres;

--
-- TOC entry 3503 (class 0 OID 0)
-- Dependencies: 219
-- Name: cliente_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cliente_id_seq OWNED BY public.cliente.id;


--
-- TOC entry 218 (class 1259 OID 16465)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    price numeric(12,2) NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16464)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3340 (class 2604 OID 16479)
-- Name: cliente id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente ALTER COLUMN id SET DEFAULT nextval('public.cliente_id_seq'::regclass);


--
-- TOC entry 3492 (class 0 OID 16455)
-- Dependencies: 216
-- Data for Name: cake_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cake_migrations (id, version, migration_name, plugin, start_time, end_time, breakpoint) FROM stdin;
1	20260218015313	CreateProducts	\N	2026-02-18 01:53:13	2026-02-18 01:53:13	f
\.


--
-- TOC entry 3496 (class 0 OID 16476)
-- Dependencies: 220
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id, nombre, email, telefono) FROM stdin;
\.


--
-- TOC entry 3494 (class 0 OID 16465)
-- Dependencies: 218
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, price) FROM stdin;
1	laptop	1500.00
2	pc	1534.00
7	wifi	32000000.00
3	ethernet	32000000.00
4	disquetera	1212300.00
8	memoria usb	55555.00
\.


--
-- TOC entry 3504 (class 0 OID 0)
-- Dependencies: 215
-- Name: cake_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cake_migrations_id_seq', 1, true);


--
-- TOC entry 3505 (class 0 OID 0)
-- Dependencies: 219
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_seq', 1, false);


--
-- TOC entry 3506 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 8, true);


--
-- TOC entry 3342 (class 2606 OID 16462)
-- Name: cake_migrations cake_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cake_migrations
    ADD CONSTRAINT cake_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3347 (class 2606 OID 16481)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- TOC entry 3345 (class 2606 OID 16469)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3343 (class 1259 OID 16463)
-- Name: version_plugin_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX version_plugin_unique ON public.cake_migrations USING btree (version, plugin);


-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict VKNqCdbdJJtxEAteQP0bMHixgEetlGgHxTrcKv19tZjmguWxijfspLihuSIgFPb

--
-- Database "api_symfony" dump
--

--
-- PostgreSQL database dump
--

\restrict pHRkvT9awed6olceLUURA7XVT2TP03YPRvYbEccUNFh7OBmDoag0lqvHBsADdcY

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3498 (class 1262 OID 16393)
-- Name: api_symfony; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE api_symfony WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE api_symfony OWNER TO postgres;

\unrestrict pHRkvT9awed6olceLUURA7XVT2TP03YPRvYbEccUNFh7OBmDoag0lqvHBsADdcY
\connect api_symfony
\restrict pHRkvT9awed6olceLUURA7XVT2TP03YPRvYbEccUNFh7OBmDoag0lqvHBsADdcY

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16394)
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 16407)
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 16406)
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16401)
-- Name: producto; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.producto (
    id integer NOT NULL,
    nombre character varying(255) NOT NULL,
    precio double precision NOT NULL
);


ALTER TABLE public.producto OWNER TO admin;

--
-- TOC entry 216 (class 1259 OID 16400)
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3488 (class 0 OID 16394)
-- Dependencies: 215
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260122234227	2026-01-22 23:42:33	198
\.


--
-- TOC entry 3492 (class 0 OID 16407)
-- Dependencies: 219
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- TOC entry 3490 (class 0 OID 16401)
-- Dependencies: 217
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.producto (id, nombre, precio) FROM stdin;
6	mango	80
3	mamey	10
2	arrayan	10
7	sandia	90
8	guisquil	34
5	maiz	90
11	pepino	17
12	marañon	60
14	ciquitrino	120
16	Tortillas	69
17	Guanaba	56
19	Jocote	75
20	Mandarina	50
21	Uvas	30
22	Sandia	58
23	Pedro perez usado remember	60
\.


--
-- TOC entry 3499 (class 0 OID 0)
-- Dependencies: 218
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- TOC entry 3500 (class 0 OID 0)
-- Dependencies: 216
-- Name: producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.producto_id_seq', 23, true);


--
-- TOC entry 3339 (class 2606 OID 16399)
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- TOC entry 3344 (class 2606 OID 16414)
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 3341 (class 2606 OID 16405)
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- TOC entry 3342 (class 1259 OID 16415)
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict pHRkvT9awed6olceLUURA7XVT2TP03YPRvYbEccUNFh7OBmDoag0lqvHBsADdcY

--
-- Database "api_yii" dump
--

--
-- PostgreSQL database dump
--

\restrict CoogwiisQa4HaXj9djZ1JpG4GX7BneP2HbVS9mWWowVzv0jmb9vmBR0jbZzZ4n1

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3480 (class 1262 OID 16489)
-- Name: api_yii; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE api_yii WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE api_yii OWNER TO postgres;

\unrestrict CoogwiisQa4HaXj9djZ1JpG4GX7BneP2HbVS9mWWowVzv0jmb9vmBR0jbZzZ4n1
\connect api_yii
\restrict CoogwiisQa4HaXj9djZ1JpG4GX7BneP2HbVS9mWWowVzv0jmb9vmBR0jbZzZ4n1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16491)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    telefono character varying(20)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16490)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cliente_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cliente_id_seq OWNER TO postgres;

--
-- TOC entry 3481 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cliente_id_seq OWNED BY public.cliente.id;


--
-- TOC entry 3327 (class 2604 OID 16494)
-- Name: cliente id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente ALTER COLUMN id SET DEFAULT nextval('public.cliente_id_seq'::regclass);


--
-- TOC entry 3474 (class 0 OID 16491)
-- Dependencies: 216
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id, nombre, email, telefono) FROM stdin;
1	edwin	edwin@gmail.com	75249775
6	manuel	manuel@gmail.com	75249775
7	klop	klop@gmail.com	73453213
5	mastodonte	mastodonte@gmail.com	74001651
10	ruisenior	ruisenior@gmail.com	79094567
11	julian alvarez	julian@gmail.com	90897867
8	mastantuono	mastantuono@gmail.com	90897867
\.


--
-- TOC entry 3482 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_seq', 11, true);


--
-- TOC entry 3329 (class 2606 OID 16496)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict CoogwiisQa4HaXj9djZ1JpG4GX7BneP2HbVS9mWWowVzv0jmb9vmBR0jbZzZ4n1

--
-- Database "bd" dump
--

--
-- PostgreSQL database dump
--

\restrict ajW2xFykbxSbaFvNtaRWnziS7iwcfobgkGjRO1qWb6jrOxZg4LFLQ8wfcDnA34f

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3470 (class 1262 OID 16389)
-- Name: bd; Type: DATABASE; Schema: -; Owner: root
--

CREATE DATABASE bd WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE bd OWNER TO root;

\unrestrict ajW2xFykbxSbaFvNtaRWnziS7iwcfobgkGjRO1qWb6jrOxZg4LFLQ8wfcDnA34f
\connect bd
\restrict ajW2xFykbxSbaFvNtaRWnziS7iwcfobgkGjRO1qWb6jrOxZg4LFLQ8wfcDnA34f

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict ajW2xFykbxSbaFvNtaRWnziS7iwcfobgkGjRO1qWb6jrOxZg4LFLQ8wfcDnA34f

--
-- Database "crud_db" dump
--

--
-- PostgreSQL database dump
--

\restrict AKBhpInu1A0TDweY0uupDM91bymS7otBZp2kdzhlQNhLTFtR5AtKu7oVT7dtvqV

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3495 (class 1262 OID 16424)
-- Name: crud_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE crud_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE crud_db OWNER TO postgres;

\unrestrict AKBhpInu1A0TDweY0uupDM91bymS7otBZp2kdzhlQNhLTFtR5AtKu7oVT7dtvqV
\connect crud_db
\restrict AKBhpInu1A0TDweY0uupDM91bymS7otBZp2kdzhlQNhLTFtR5AtKu7oVT7dtvqV

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16444)
-- Name: cake_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cake_migrations (
    id integer NOT NULL,
    version bigint NOT NULL,
    migration_name character varying(100) DEFAULT NULL::character varying,
    plugin character varying(100) DEFAULT NULL::character varying,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    breakpoint boolean DEFAULT false NOT NULL
);


ALTER TABLE public.cake_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16443)
-- Name: cake_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cake_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cake_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16435)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying(150) NOT NULL,
    price numeric(10,2) NOT NULL,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16434)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.products_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.products_id_seq OWNER TO postgres;

--
-- TOC entry 3496 (class 0 OID 0)
-- Dependencies: 215
-- Name: products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


--
-- TOC entry 3332 (class 2604 OID 16438)
-- Name: products id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);


--
-- TOC entry 3489 (class 0 OID 16444)
-- Dependencies: 218
-- Data for Name: cake_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cake_migrations (id, version, migration_name, plugin, start_time, end_time, breakpoint) FROM stdin;
\.


--
-- TOC entry 3487 (class 0 OID 16435)
-- Dependencies: 216
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, price, created, modified) FROM stdin;
3	edwin	2.00	2026-02-18 01:32:48.091856	2026-02-18 01:32:48.091897
4	guanaba	90.00	2026-02-18 01:34:29.688662	2026-02-18 01:34:29.688711
1	mbappe	2.00	2026-02-18 01:32:46.179852	2026-02-18 01:36:21.082983
\.


--
-- TOC entry 3497 (class 0 OID 0)
-- Dependencies: 217
-- Name: cake_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cake_migrations_id_seq', 1, false);


--
-- TOC entry 3498 (class 0 OID 0)
-- Dependencies: 215
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 4, true);


--
-- TOC entry 3341 (class 2606 OID 16451)
-- Name: cake_migrations cake_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cake_migrations
    ADD CONSTRAINT cake_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3339 (class 2606 OID 16442)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3342 (class 1259 OID 16452)
-- Name: version_plugin_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX version_plugin_unique ON public.cake_migrations USING btree (version, plugin);


-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict AKBhpInu1A0TDweY0uupDM91bymS7otBZp2kdzhlQNhLTFtR5AtKu7oVT7dtvqV

--
-- Database "crud_yii" dump
--

--
-- PostgreSQL database dump
--

\restrict guvSOV20IfeEEEEb0aQ1AVcht3YJQfkzejaiiAuSrScjuxvU4lnPJzEkDtjwTAa

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3480 (class 1262 OID 16474)
-- Name: crud_yii; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE crud_yii WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE crud_yii OWNER TO postgres;

\unrestrict guvSOV20IfeEEEEb0aQ1AVcht3YJQfkzejaiiAuSrScjuxvU4lnPJzEkDtjwTAa
\connect crud_yii
\restrict guvSOV20IfeEEEEb0aQ1AVcht3YJQfkzejaiiAuSrScjuxvU4lnPJzEkDtjwTAa

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16483)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id integer NOT NULL,
    nombre character varying(100),
    email character varying(100),
    telefono character varying(20)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16482)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cliente_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cliente_id_seq OWNER TO postgres;

--
-- TOC entry 3481 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cliente_id_seq OWNED BY public.cliente.id;


--
-- TOC entry 3327 (class 2604 OID 16486)
-- Name: cliente id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente ALTER COLUMN id SET DEFAULT nextval('public.cliente_id_seq'::regclass);


--
-- TOC entry 3474 (class 0 OID 16483)
-- Dependencies: 216
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id, nombre, email, telefono) FROM stdin;
2	francisco	francisco@gmail.com	72403959
3	sonia	sonia@gmail.com	74803239
4	sofia	sofia@gmail.com	78909657
\.


--
-- TOC entry 3482 (class 0 OID 0)
-- Dependencies: 215
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_seq', 4, true);


--
-- TOC entry 3329 (class 2606 OID 16488)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict guvSOV20IfeEEEEb0aQ1AVcht3YJQfkzejaiiAuSrScjuxvU4lnPJzEkDtjwTAa

--
-- Database "db_prueba" dump
--

--
-- PostgreSQL database dump
--

\restrict RdsmEFFteDBpjPpIfWTnhCzGHUtdZyGpQAMNnhAirW4rBVNvVbU9jbiNVLJ71A2

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3470 (class 1262 OID 16392)
-- Name: db_prueba; Type: DATABASE; Schema: -; Owner: admin
--

CREATE DATABASE db_prueba WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE db_prueba OWNER TO admin;

\unrestrict RdsmEFFteDBpjPpIfWTnhCzGHUtdZyGpQAMNnhAirW4rBVNvVbU9jbiNVLJ71A2
\connect db_prueba
\restrict RdsmEFFteDBpjPpIfWTnhCzGHUtdZyGpQAMNnhAirW4rBVNvVbU9jbiNVLJ71A2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict RdsmEFFteDBpjPpIfWTnhCzGHUtdZyGpQAMNnhAirW4rBVNvVbU9jbiNVLJ71A2

--
-- Database "laravel" dump
--

--
-- PostgreSQL database dump
--

\restrict fRGg1EBrWetzBFR472tTVwdPmmy7s8EzOS1PCwVbZ2hUHRf7MliUhuiIp9EqqFG

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3565 (class 1262 OID 16505)
-- Name: laravel; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE laravel WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE laravel OWNER TO postgres;

\unrestrict fRGg1EBrWetzBFR472tTVwdPmmy7s8EzOS1PCwVbZ2hUHRf7MliUhuiIp9EqqFG
\connect laravel
\restrict fRGg1EBrWetzBFR472tTVwdPmmy7s8EzOS1PCwVbZ2hUHRf7MliUhuiIp9EqqFG

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16540)
-- Name: cache; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cache (
    key character varying(255) NOT NULL,
    value text NOT NULL,
    expiration integer NOT NULL
);


ALTER TABLE public.cache OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16548)
-- Name: cache_locks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cache_locks (
    key character varying(255) NOT NULL,
    owner character varying(255) NOT NULL,
    expiration integer NOT NULL
);


ALTER TABLE public.cache_locks OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16574)
-- Name: failed_jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.failed_jobs (
    id bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.failed_jobs OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16573)
-- Name: failed_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.failed_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.failed_jobs_id_seq OWNER TO postgres;

--
-- TOC entry 3566 (class 0 OID 0)
-- Dependencies: 226
-- Name: failed_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.failed_jobs_id_seq OWNED BY public.failed_jobs.id;


--
-- TOC entry 225 (class 1259 OID 16566)
-- Name: job_batches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_batches (
    id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text NOT NULL,
    options text,
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer
);


ALTER TABLE public.job_batches OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16557)
-- Name: jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    queue character varying(255) NOT NULL,
    payload text NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16556)
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jobs_id_seq OWNER TO postgres;

--
-- TOC entry 3567 (class 0 OID 0)
-- Dependencies: 223
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- TOC entry 216 (class 1259 OID 16507)
-- Name: migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);


ALTER TABLE public.migrations OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16506)
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.migrations_id_seq OWNER TO postgres;

--
-- TOC entry 3568 (class 0 OID 0)
-- Dependencies: 215
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- TOC entry 219 (class 1259 OID 16524)
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    email character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    created_at timestamp(0) without time zone
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16586)
-- Name: posts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    content text,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


ALTER TABLE public.posts OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16585)
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.posts_id_seq OWNER TO postgres;

--
-- TOC entry 3569 (class 0 OID 0)
-- Dependencies: 228
-- Name: posts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.posts_id_seq OWNED BY public.posts.id;


--
-- TOC entry 220 (class 1259 OID 16531)
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id character varying(255) NOT NULL,
    user_id bigint,
    ip_address character varying(45),
    user_agent text,
    payload text NOT NULL,
    last_activity integer NOT NULL
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16514)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    email_verified_at timestamp(0) without time zone,
    password character varying(255) NOT NULL,
    remember_token character varying(100),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16513)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 3570 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 3370 (class 2604 OID 16577)
-- Name: failed_jobs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.failed_jobs ALTER COLUMN id SET DEFAULT nextval('public.failed_jobs_id_seq'::regclass);


--
-- TOC entry 3369 (class 2604 OID 16560)
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- TOC entry 3367 (class 2604 OID 16510)
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- TOC entry 3372 (class 2604 OID 16589)
-- Name: posts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts ALTER COLUMN id SET DEFAULT nextval('public.posts_id_seq'::regclass);


--
-- TOC entry 3368 (class 2604 OID 16517)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 3551 (class 0 OID 16540)
-- Dependencies: 221
-- Data for Name: cache; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cache (key, value, expiration) FROM stdin;
\.


--
-- TOC entry 3552 (class 0 OID 16548)
-- Dependencies: 222
-- Data for Name: cache_locks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cache_locks (key, owner, expiration) FROM stdin;
\.


--
-- TOC entry 3557 (class 0 OID 16574)
-- Dependencies: 227
-- Data for Name: failed_jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.failed_jobs (id, uuid, connection, queue, payload, exception, failed_at) FROM stdin;
\.


--
-- TOC entry 3555 (class 0 OID 16566)
-- Dependencies: 225
-- Data for Name: job_batches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_batches (id, name, total_jobs, pending_jobs, failed_jobs, failed_job_ids, options, cancelled_at, created_at, finished_at) FROM stdin;
\.


--
-- TOC entry 3554 (class 0 OID 16557)
-- Dependencies: 224
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jobs (id, queue, payload, attempts, reserved_at, available_at, created_at) FROM stdin;
\.


--
-- TOC entry 3546 (class 0 OID 16507)
-- Dependencies: 216
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.migrations (id, migration, batch) FROM stdin;
1	0001_01_01_000000_create_users_table	1
2	0001_01_01_000001_create_cache_table	1
3	0001_01_01_000002_create_jobs_table	1
4	2026_02_25_230729_create_posts_table	2
\.


--
-- TOC entry 3549 (class 0 OID 16524)
-- Dependencies: 219
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_tokens (email, token, created_at) FROM stdin;
\.


--
-- TOC entry 3559 (class 0 OID 16586)
-- Dependencies: 229
-- Data for Name: posts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.posts (id, title, content, created_at, updated_at) FROM stdin;
2	pelon	pison	2026-02-25 23:21:59	2026-02-25 23:22:50
3	gallo	portillo	2026-02-25 23:22:10	2026-02-25 23:23:12
4	mbappe	donatello	2026-02-25 23:22:23	2026-02-25 23:23:22
5	mastantuono	argentino	2026-02-25 23:22:39	2026-02-25 23:23:31
13	quinto post	Contenido	2026-02-26 00:00:38	2026-02-26 00:00:38
14	Primer post	Contenido	2026-02-26 00:02:07	2026-02-26 00:02:07
15	segundo post	Contenido	2026-02-26 00:02:12	2026-02-26 00:02:12
16	tercer post	Contenido	2026-02-26 00:02:17	2026-02-26 00:02:17
17	cuarto post	Contenido	2026-02-26 00:02:18	2026-02-26 00:02:18
18	quinto post	Contenido	2026-02-26 00:02:19	2026-02-26 00:02:19
19	Primer post	Contenido	2026-02-26 00:04:17	2026-02-26 00:04:17
7	cualquier post	Contenido	2026-02-25 23:23:57	2026-02-26 00:05:07
\.


--
-- TOC entry 3550 (class 0 OID 16531)
-- Dependencies: 220
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, user_id, ip_address, user_agent, payload, last_activity) FROM stdin;
2V769gqxk71xIUXiZIVat3uGgSoUtL6oSuQJX4tq	\N	127.0.0.1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cursor/2.5.22 Chrome/142.0.7444.265 Electron/39.4.0 Safari/537.36	YTozOntzOjY6Il90b2tlbiI7czo0MDoia0N3Z1d3SnRyOEd2YmgwOUd0WFpKRVJ2MjJmSk1hYU1WZHVGRkZScyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7czo1OiJyb3V0ZSI7Tjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772061840
dr0X2wDTQENfsgOQw8qVgwAHhbIYtVDAcGXCKmeD	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoiTVJsaEE1ZTVOdjhnMHViZ29yTHFjTVBYVGJHZFdYZHEwVVRzN05KTyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062687
qRZPVaxIS5Q8xtoMaP270DfFvPkjSFdMgOYVcxoX	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoidXdCSDFzaVRtZHlpOFpxZU43SjVkZlBXS2RvTVFNcUFRSWNzdDZTbyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062719
1TiVEi0IMZwH9I9exoNQybGUNqaWlbv1l2GS2Dco	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoiUTl2eUh0eFVsUEphWGVDTkcyTVc3RHBDMTFyeVd3bTBiWDF3dXpYcSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062766
ajlkIaLwr4Ia4XHPsFiIydcXPzcjVxOH12vK6wk2	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoiREtiMjh6dld6cVJ1bzQ2RkdzUzM1RzIyUUdsUGxXYXQyVUFtMEVrNiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062785
8l2kBkm8aBRp4bOI0bDXyjlTiOKEfSJ0FZboJOD2	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiUE82cUFuRktRaEZ3dnVhSzRZZk44d1VCZ21qRlczaGVVYVN1b0ZWRCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062791
EWAd8RTSLtDcYatN9dyElT1uePSa07qFUKHBVxe6	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoid21mcVh5Q2FkMFd4R3o2bDlER1pwcW81UHE0T01GSHpxNFVFZWs3OSI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062808
7GR2mvuSq3ALco4Z8g9K7AB3dySVDKcIz8f0Z8DV	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiYmFuTkF3N0Y3dFBUQmdGdEFoRVpFNnFzZ3NHWlVDdTlINHhONlJqUSI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062967
rq2RHGXgtKVaApvNTzrAZiEKBqZ7yqRJfmKbQwZv	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoieHdkSDVyN09wb3NCVlNHWWpCWldJZWFnamE0WEpOVXJtVTlqMkJuaCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062978
WKeODgWuxOlJdWYciycLbgA4jCryM6BdkFiX0UlJ	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiS1FiVFRWQ0pGT0NiOTNuUlREWVJIdHhZUWZybmt6dUFYQ2YyaTZIeCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063061
V2uTsArKFlImqpCzKKURl5Z790yGDUbVwEI3NS5T	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoieVJoS1JEMkpyWkZZTW42ZXJSMGRVN1dCc3c1VDkyZFAyN1FDQ0lpSCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063126
v5AMPJXYBlsVZXq6LrDBOQsTOkFjil8xLmkVh9So	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiYWViVnVjZUU2Ym50c3V1THR4OHcwd3c0eG8yZzlsTzhGUFRKc3pJQyI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063187
9738GVf63bUtRuUbPrb0m4WIC0zWN7VnFZdpf8BY	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiazhoMUFaN2RhaWlZRWxwQUxPUzdSMjY1bDQ0TTdiQjVKcGtyRm1QdCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063206
wj5E068hlTH9QmyxjSiA2mu8k4bqqXQBKAgulMjs	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiS2FvV21LbjdBWEhBVTRiMWpHcExGeERnSE05Q3oyajRPOWFtcVB5ayI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064127
3dMnT07Fi55pjlcLEv5xMfa8pMA4vq9PNFIwSvFT	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiOGs0VlhmVzFJdFNGaXhGNGk0ZDNjRkZhd3NFOHcwVEFvcWhkaThLaiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064132
HQn5ByajbFp52Rt05xJJs197OktZIWCYcICWgywX	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiVGI5a0dhTWlIME50OVdSV1Y2MVRXSjM2bjhUY3E0aGdNQlZFMGxDeiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064137
00QHOBFD3ZOHuc9k6THqYmUqf8u3nIW0ua4yv69M	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoibHgxYjhFM0IzQTNNTzN0RHF2Uzcyek5PSFFFOHI1b2JzNTlQNVU0QyI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064138
CApGOkNVtRWRfiL9yD08XyiWGo1PpOQMq3ny9KHA	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiSTJNSnczWEZxdkgzcjAyb0J4bXBWYTE2R3pwNmhzaW5CSVJFejFQSiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064139
Ikd6PR0TrSlTqFLZ5tAB7FVrOmFskkurbSRvmWxr	\N	127.0.0.1	PostmanRuntime/7.51.1	YTozOntzOjY6Il90b2tlbiI7czo0MDoiN29pb21YSjFURHpLNHVrQllCNXdwaWJkODQzODZCWnpMV2ZoVVYxTSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzM6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMvMSI7czo1OiJyb3V0ZSI7czoxMDoicG9zdHMuc2hvdyI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=	1772064377
\.


--
-- TOC entry 3548 (class 0 OID 16514)
-- Dependencies: 218
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, email_verified_at, password, remember_token, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3571 (class 0 OID 0)
-- Dependencies: 226
-- Name: failed_jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.failed_jobs_id_seq', 1, false);


--
-- TOC entry 3572 (class 0 OID 0)
-- Dependencies: 223
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jobs_id_seq', 1, false);


--
-- TOC entry 3573 (class 0 OID 0)
-- Dependencies: 215
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.migrations_id_seq', 4, true);


--
-- TOC entry 3574 (class 0 OID 0)
-- Dependencies: 228
-- Name: posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.posts_id_seq', 19, true);


--
-- TOC entry 3575 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 3390 (class 2606 OID 16554)
-- Name: cache_locks cache_locks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cache_locks
    ADD CONSTRAINT cache_locks_pkey PRIMARY KEY (key);


--
-- TOC entry 3387 (class 2606 OID 16546)
-- Name: cache cache_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cache
    ADD CONSTRAINT cache_pkey PRIMARY KEY (key);


--
-- TOC entry 3397 (class 2606 OID 16582)
-- Name: failed_jobs failed_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.failed_jobs
    ADD CONSTRAINT failed_jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 3399 (class 2606 OID 16584)
-- Name: failed_jobs failed_jobs_uuid_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.failed_jobs
    ADD CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid);


--
-- TOC entry 3395 (class 2606 OID 16572)
-- Name: job_batches job_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_batches
    ADD CONSTRAINT job_batches_pkey PRIMARY KEY (id);


--
-- TOC entry 3392 (class 2606 OID 16564)
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 3374 (class 2606 OID 16512)
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3380 (class 2606 OID 16530)
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email);


--
-- TOC entry 3401 (class 2606 OID 16593)
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- TOC entry 3383 (class 2606 OID 16537)
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 3376 (class 2606 OID 16523)
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 3378 (class 2606 OID 16521)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3385 (class 1259 OID 16547)
-- Name: cache_expiration_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cache_expiration_index ON public.cache USING btree (expiration);


--
-- TOC entry 3388 (class 1259 OID 16555)
-- Name: cache_locks_expiration_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cache_locks_expiration_index ON public.cache_locks USING btree (expiration);


--
-- TOC entry 3393 (class 1259 OID 16565)
-- Name: jobs_queue_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX jobs_queue_index ON public.jobs USING btree (queue);


--
-- TOC entry 3381 (class 1259 OID 16539)
-- Name: sessions_last_activity_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sessions_last_activity_index ON public.sessions USING btree (last_activity);


--
-- TOC entry 3384 (class 1259 OID 16538)
-- Name: sessions_user_id_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sessions_user_id_index ON public.sessions USING btree (user_id);


-- Completed on 2026-03-16 15:14:08 CST

--
-- PostgreSQL database dump complete
--

\unrestrict fRGg1EBrWetzBFR472tTVwdPmmy7s8EzOS1PCwVbZ2hUHRf7MliUhuiIp9EqqFG

--
-- Database "mi_api" dump
--

--
-- PostgreSQL database dump
--

\restrict BlMwfV92EDJV8iPAoRQZXdfnZsPRwgkntUgdChfmZEDLFrDiUUfqcALyMlDxgj4

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:08 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3492 (class 1262 OID 16416)
-- Name: mi_api; Type: DATABASE; Schema: -; Owner: admin
--

CREATE DATABASE mi_api WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE mi_api OWNER TO admin;

\unrestrict BlMwfV92EDJV8iPAoRQZXdfnZsPRwgkntUgdChfmZEDLFrDiUUfqcALyMlDxgj4
\connect mi_api
\restrict BlMwfV92EDJV8iPAoRQZXdfnZsPRwgkntUgdChfmZEDLFrDiUUfqcALyMlDxgj4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16426)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying(150) NOT NULL,
    price numeric(10,2) NOT NULL,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16425)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.products_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.products_id_seq OWNER TO postgres;

--
-- TOC entry 3493 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


--
-- TOC entry 216 (class 1259 OID 16418)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying(100),
    email character varying(100)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16417)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 3494 (class 0 OID 0)
-- Dependencies: 215
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 3333 (class 2604 OID 16429)
-- Name: products id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);


--
-- TOC entry 3332 (class 2604 OID 16421)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 3486 (class 0 OID 16426)
-- Dependencies: 218
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, name, price, created, modified) FROM stdin;
\.


--
-- TOC entry 3484 (class 0 OID 16418)
-- Dependencies: 216
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email) FROM stdin;
\.


--
-- TOC entry 3495 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- TOC entry 3496 (class 0 OID 0)
-- Dependencies: 215
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 3339 (class 2606 OID 16433)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3337 (class 2606 OID 16423)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


-- Completed on 2026-03-16 15:14:09 CST

--
-- PostgreSQL database dump complete
--

\unrestrict BlMwfV92EDJV8iPAoRQZXdfnZsPRwgkntUgdChfmZEDLFrDiUUfqcALyMlDxgj4

--
-- Database "new" dump
--

--
-- PostgreSQL database dump
--

\restrict pqrhBLKPlRhcPTf6EazAHLWlrxrWNoZ0pFw7ckz5FeDknDgaidwfvQtYn13Lwep

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:09 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3565 (class 1262 OID 16594)
-- Name: new; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE new WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE new OWNER TO postgres;

\unrestrict pqrhBLKPlRhcPTf6EazAHLWlrxrWNoZ0pFw7ckz5FeDknDgaidwfvQtYn13Lwep
\connect new
\restrict pqrhBLKPlRhcPTf6EazAHLWlrxrWNoZ0pFw7ckz5FeDknDgaidwfvQtYn13Lwep

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16595)
-- Name: cache; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cache (
    key character varying(255) NOT NULL,
    value text NOT NULL,
    expiration integer NOT NULL
);


ALTER TABLE public.cache OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16600)
-- Name: cache_locks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cache_locks (
    key character varying(255) NOT NULL,
    owner character varying(255) NOT NULL,
    expiration integer NOT NULL
);


ALTER TABLE public.cache_locks OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16605)
-- Name: failed_jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.failed_jobs (
    id bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.failed_jobs OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16611)
-- Name: failed_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.failed_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.failed_jobs_id_seq OWNER TO postgres;

--
-- TOC entry 3566 (class 0 OID 0)
-- Dependencies: 218
-- Name: failed_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.failed_jobs_id_seq OWNED BY public.failed_jobs.id;


--
-- TOC entry 219 (class 1259 OID 16612)
-- Name: job_batches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_batches (
    id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text NOT NULL,
    options text,
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer
);


ALTER TABLE public.job_batches OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16617)
-- Name: jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    queue character varying(255) NOT NULL,
    payload text NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16622)
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jobs_id_seq OWNER TO postgres;

--
-- TOC entry 3567 (class 0 OID 0)
-- Dependencies: 221
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- TOC entry 222 (class 1259 OID 16623)
-- Name: migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);


ALTER TABLE public.migrations OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16626)
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.migrations_id_seq OWNER TO postgres;

--
-- TOC entry 3568 (class 0 OID 0)
-- Dependencies: 223
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- TOC entry 224 (class 1259 OID 16627)
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    email character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    created_at timestamp(0) without time zone
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16632)
-- Name: posts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    content text,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


ALTER TABLE public.posts OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16637)
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.posts_id_seq OWNER TO postgres;

--
-- TOC entry 3569 (class 0 OID 0)
-- Dependencies: 226
-- Name: posts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.posts_id_seq OWNED BY public.posts.id;


--
-- TOC entry 227 (class 1259 OID 16638)
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id character varying(255) NOT NULL,
    user_id bigint,
    ip_address character varying(45),
    user_agent text,
    payload text NOT NULL,
    last_activity integer NOT NULL
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16643)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    email_verified_at timestamp(0) without time zone,
    password character varying(255) NOT NULL,
    remember_token character varying(100),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16648)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 3570 (class 0 OID 0)
-- Dependencies: 229
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 3367 (class 2604 OID 16649)
-- Name: failed_jobs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.failed_jobs ALTER COLUMN id SET DEFAULT nextval('public.failed_jobs_id_seq'::regclass);


--
-- TOC entry 3369 (class 2604 OID 16650)
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- TOC entry 3370 (class 2604 OID 16651)
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- TOC entry 3371 (class 2604 OID 16652)
-- Name: posts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts ALTER COLUMN id SET DEFAULT nextval('public.posts_id_seq'::regclass);


--
-- TOC entry 3372 (class 2604 OID 16653)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 3545 (class 0 OID 16595)
-- Dependencies: 215
-- Data for Name: cache; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cache (key, value, expiration) FROM stdin;
\.


--
-- TOC entry 3546 (class 0 OID 16600)
-- Dependencies: 216
-- Data for Name: cache_locks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cache_locks (key, owner, expiration) FROM stdin;
\.


--
-- TOC entry 3547 (class 0 OID 16605)
-- Dependencies: 217
-- Data for Name: failed_jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.failed_jobs (id, uuid, connection, queue, payload, exception, failed_at) FROM stdin;
\.


--
-- TOC entry 3549 (class 0 OID 16612)
-- Dependencies: 219
-- Data for Name: job_batches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_batches (id, name, total_jobs, pending_jobs, failed_jobs, failed_job_ids, options, cancelled_at, created_at, finished_at) FROM stdin;
\.


--
-- TOC entry 3550 (class 0 OID 16617)
-- Dependencies: 220
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jobs (id, queue, payload, attempts, reserved_at, available_at, created_at) FROM stdin;
\.


--
-- TOC entry 3552 (class 0 OID 16623)
-- Dependencies: 222
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.migrations (id, migration, batch) FROM stdin;
1	0001_01_01_000000_create_users_table	1
2	0001_01_01_000001_create_cache_table	1
3	0001_01_01_000002_create_jobs_table	1
4	2026_02_25_230729_create_posts_table	2
\.


--
-- TOC entry 3554 (class 0 OID 16627)
-- Dependencies: 224
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_tokens (email, token, created_at) FROM stdin;
\.


--
-- TOC entry 3555 (class 0 OID 16632)
-- Dependencies: 225
-- Data for Name: posts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.posts (id, title, content, created_at, updated_at) FROM stdin;
2	pelon	pison	2026-02-25 23:21:59	2026-02-25 23:22:50
3	gallo	portillo	2026-02-25 23:22:10	2026-02-25 23:23:12
4	mbappe	donatello	2026-02-25 23:22:23	2026-02-25 23:23:22
5	mastantuono	argentino	2026-02-25 23:22:39	2026-02-25 23:23:31
13	quinto post	Contenido	2026-02-26 00:00:38	2026-02-26 00:00:38
14	Primer post	Contenido	2026-02-26 00:02:07	2026-02-26 00:02:07
15	segundo post	Contenido	2026-02-26 00:02:12	2026-02-26 00:02:12
16	tercer post	Contenido	2026-02-26 00:02:17	2026-02-26 00:02:17
17	cuarto post	Contenido	2026-02-26 00:02:18	2026-02-26 00:02:18
18	quinto post	Contenido	2026-02-26 00:02:19	2026-02-26 00:02:19
19	Primer post	Contenido	2026-02-26 00:04:17	2026-02-26 00:04:17
7	cualquier post	Contenido	2026-02-25 23:23:57	2026-02-26 00:05:07
\.


--
-- TOC entry 3557 (class 0 OID 16638)
-- Dependencies: 227
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, user_id, ip_address, user_agent, payload, last_activity) FROM stdin;
2V769gqxk71xIUXiZIVat3uGgSoUtL6oSuQJX4tq	\N	127.0.0.1	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cursor/2.5.22 Chrome/142.0.7444.265 Electron/39.4.0 Safari/537.36	YTozOntzOjY6Il90b2tlbiI7czo0MDoia0N3Z1d3SnRyOEd2YmgwOUd0WFpKRVJ2MjJmSk1hYU1WZHVGRkZScyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7czo1OiJyb3V0ZSI7Tjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772061840
dr0X2wDTQENfsgOQw8qVgwAHhbIYtVDAcGXCKmeD	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoiTVJsaEE1ZTVOdjhnMHViZ29yTHFjTVBYVGJHZFdYZHEwVVRzN05KTyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062687
qRZPVaxIS5Q8xtoMaP270DfFvPkjSFdMgOYVcxoX	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoidXdCSDFzaVRtZHlpOFpxZU43SjVkZlBXS2RvTVFNcUFRSWNzdDZTbyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062719
1TiVEi0IMZwH9I9exoNQybGUNqaWlbv1l2GS2Dco	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoiUTl2eUh0eFVsUEphWGVDTkcyTVc3RHBDMTFyeVd3bTBiWDF3dXpYcSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062766
ajlkIaLwr4Ia4XHPsFiIydcXPzcjVxOH12vK6wk2	\N	127.0.0.1	curl/8.5.0	YTozOntzOjY6Il90b2tlbiI7czo0MDoiREtiMjh6dld6cVJ1bzQ2RkdzUzM1RzIyUUdsUGxXYXQyVUFtMEVrNiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMiO3M6NToicm91dGUiO3M6MTE6InBvc3RzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062785
8l2kBkm8aBRp4bOI0bDXyjlTiOKEfSJ0FZboJOD2	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiUE82cUFuRktRaEZ3dnVhSzRZZk44d1VCZ21qRlczaGVVYVN1b0ZWRCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062791
EWAd8RTSLtDcYatN9dyElT1uePSa07qFUKHBVxe6	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoid21mcVh5Q2FkMFd4R3o2bDlER1pwcW81UHE0T01GSHpxNFVFZWs3OSI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062808
7GR2mvuSq3ALco4Z8g9K7AB3dySVDKcIz8f0Z8DV	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiYmFuTkF3N0Y3dFBUQmdGdEFoRVpFNnFzZ3NHWlVDdTlINHhONlJqUSI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062967
rq2RHGXgtKVaApvNTzrAZiEKBqZ7yqRJfmKbQwZv	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoieHdkSDVyN09wb3NCVlNHWWpCWldJZWFnamE0WEpOVXJtVTlqMkJuaCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772062978
WKeODgWuxOlJdWYciycLbgA4jCryM6BdkFiX0UlJ	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiS1FiVFRWQ0pGT0NiOTNuUlREWVJIdHhZUWZybmt6dUFYQ2YyaTZIeCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063061
V2uTsArKFlImqpCzKKURl5Z790yGDUbVwEI3NS5T	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoieVJoS1JEMkpyWkZZTW42ZXJSMGRVN1dCc3c1VDkyZFAyN1FDQ0lpSCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063126
v5AMPJXYBlsVZXq6LrDBOQsTOkFjil8xLmkVh9So	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiYWViVnVjZUU2Ym50c3V1THR4OHcwd3c0eG8yZzlsTzhGUFRKc3pJQyI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063187
9738GVf63bUtRuUbPrb0m4WIC0zWN7VnFZdpf8BY	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiazhoMUFaN2RhaWlZRWxwQUxPUzdSMjY1bDQ0TTdiQjVKcGtyRm1QdCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772063206
wj5E068hlTH9QmyxjSiA2mu8k4bqqXQBKAgulMjs	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiS2FvV21LbjdBWEhBVTRiMWpHcExGeERnSE05Q3oyajRPOWFtcVB5ayI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064127
3dMnT07Fi55pjlcLEv5xMfa8pMA4vq9PNFIwSvFT	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiOGs0VlhmVzFJdFNGaXhGNGk0ZDNjRkZhd3NFOHcwVEFvcWhkaThLaiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064132
HQn5ByajbFp52Rt05xJJs197OktZIWCYcICWgywX	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiVGI5a0dhTWlIME50OVdSV1Y2MVRXSjM2bjhUY3E0aGdNQlZFMGxDeiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064137
00QHOBFD3ZOHuc9k6THqYmUqf8u3nIW0ua4yv69M	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoibHgxYjhFM0IzQTNNTzN0RHF2Uzcyek5PSFFFOHI1b2JzNTlQNVU0QyI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064138
CApGOkNVtRWRfiL9yD08XyiWGo1PpOQMq3ny9KHA	\N	127.0.0.1	curl/8.5.0	YToyOntzOjY6Il90b2tlbiI7czo0MDoiSTJNSnczWEZxdkgzcjAyb0J4bXBWYTE2R3pwNmhzaW5CSVJFejFQSiI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==	1772064139
Ikd6PR0TrSlTqFLZ5tAB7FVrOmFskkurbSRvmWxr	\N	127.0.0.1	PostmanRuntime/7.51.1	YTozOntzOjY6Il90b2tlbiI7czo0MDoiN29pb21YSjFURHpLNHVrQllCNXdwaWJkODQzODZCWnpMV2ZoVVYxTSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzM6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvcG9zdHMvMSI7czo1OiJyb3V0ZSI7czoxMDoicG9zdHMuc2hvdyI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=	1772064377
\.


--
-- TOC entry 3558 (class 0 OID 16643)
-- Dependencies: 228
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, email_verified_at, password, remember_token, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 3571 (class 0 OID 0)
-- Dependencies: 218
-- Name: failed_jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.failed_jobs_id_seq', 1, false);


--
-- TOC entry 3572 (class 0 OID 0)
-- Dependencies: 221
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jobs_id_seq', 1, false);


--
-- TOC entry 3573 (class 0 OID 0)
-- Dependencies: 223
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.migrations_id_seq', 4, true);


--
-- TOC entry 3574 (class 0 OID 0)
-- Dependencies: 226
-- Name: posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.posts_id_seq', 19, true);


--
-- TOC entry 3575 (class 0 OID 0)
-- Dependencies: 229
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 3378 (class 2606 OID 16655)
-- Name: cache_locks cache_locks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cache_locks
    ADD CONSTRAINT cache_locks_pkey PRIMARY KEY (key);


--
-- TOC entry 3375 (class 2606 OID 16657)
-- Name: cache cache_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cache
    ADD CONSTRAINT cache_pkey PRIMARY KEY (key);


--
-- TOC entry 3380 (class 2606 OID 16659)
-- Name: failed_jobs failed_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.failed_jobs
    ADD CONSTRAINT failed_jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 3382 (class 2606 OID 16661)
-- Name: failed_jobs failed_jobs_uuid_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.failed_jobs
    ADD CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid);


--
-- TOC entry 3384 (class 2606 OID 16663)
-- Name: job_batches job_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_batches
    ADD CONSTRAINT job_batches_pkey PRIMARY KEY (id);


--
-- TOC entry 3386 (class 2606 OID 16665)
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 3389 (class 2606 OID 16667)
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3391 (class 2606 OID 16669)
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email);


--
-- TOC entry 3393 (class 2606 OID 16671)
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- TOC entry 3396 (class 2606 OID 16673)
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 3399 (class 2606 OID 16675)
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 3401 (class 2606 OID 16677)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3373 (class 1259 OID 16678)
-- Name: cache_expiration_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cache_expiration_index ON public.cache USING btree (expiration);


--
-- TOC entry 3376 (class 1259 OID 16679)
-- Name: cache_locks_expiration_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cache_locks_expiration_index ON public.cache_locks USING btree (expiration);


--
-- TOC entry 3387 (class 1259 OID 16680)
-- Name: jobs_queue_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX jobs_queue_index ON public.jobs USING btree (queue);


--
-- TOC entry 3394 (class 1259 OID 16681)
-- Name: sessions_last_activity_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sessions_last_activity_index ON public.sessions USING btree (last_activity);


--
-- TOC entry 3397 (class 1259 OID 16682)
-- Name: sessions_user_id_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sessions_user_id_index ON public.sessions USING btree (user_id);


-- Completed on 2026-03-16 15:14:09 CST

--
-- PostgreSQL database dump complete
--

\unrestrict pqrhBLKPlRhcPTf6EazAHLWlrxrWNoZ0pFw7ckz5FeDknDgaidwfvQtYn13Lwep

--
-- Database "phalcon" dump
--

--
-- PostgreSQL database dump
--

\restrict zGB7Xtbk6fyg1mP3XIN3Q9CakWDD9Azel7gUz8favQ7atetPT2Zgwgxb6856ocs

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:09 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3480 (class 1262 OID 16497)
-- Name: phalcon; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE phalcon WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE phalcon OWNER TO postgres;

\unrestrict zGB7Xtbk6fyg1mP3XIN3Q9CakWDD9Azel7gUz8favQ7atetPT2Zgwgxb6856ocs
\connect phalcon
\restrict zGB7Xtbk6fyg1mP3XIN3Q9CakWDD9Azel7gUz8favQ7atetPT2Zgwgxb6856ocs

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16499)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    email character varying(150) NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16498)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuarios_id_seq OWNER TO postgres;

--
-- TOC entry 3481 (class 0 OID 0)
-- Dependencies: 215
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- TOC entry 3327 (class 2604 OID 16502)
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- TOC entry 3474 (class 0 OID 16499)
-- Dependencies: 216
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, nombre, email) FROM stdin;
2	MANUEL	MANUEL@GMAIL.COM
4	GUSTAVO	GUSTAVO@GMAIL.COM
3	MBAPPE	MBAPPE@GMAIL.COM
5	MASTANTUONO	MASTANTUONO@GMAIL.COM
6	PETRONILO	PETRONILO@GMAIL.COM
7	julian aklvarez	edwinfrcperez@gmail.com
8	sonia	edwin_frc@hotmail.com
\.


--
-- TOC entry 3482 (class 0 OID 0)
-- Dependencies: 215
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 8, true);


--
-- TOC entry 3329 (class 2606 OID 16504)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


-- Completed on 2026-03-16 15:14:09 CST

--
-- PostgreSQL database dump complete
--

\unrestrict zGB7Xtbk6fyg1mP3XIN3Q9CakWDD9Azel7gUz8favQ7atetPT2Zgwgxb6856ocs

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

\restrict h14Om9c85tTyvSvj4Fch8gBBbwJOkQkCPzuR4S6Ec5IaYaqC5jMRTkyA6hSFE5P

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:09 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2026-03-16 15:14:09 CST

--
-- PostgreSQL database dump complete
--

\unrestrict h14Om9c85tTyvSvj4Fch8gBBbwJOkQkCPzuR4S6Ec5IaYaqC5jMRTkyA6hSFE5P

--
-- Database "symfony" dump
--

--
-- PostgreSQL database dump
--

\restrict sG2QAgq9dMbL9ejvd3bCykORoYNVGJGW8Rp9AJJz9zQGwjnkXuKVQf1rdWowOjJ

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-03-16 15:14:09 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3498 (class 1262 OID 16683)
-- Name: symfony; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE symfony WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_SV.UTF-8';


ALTER DATABASE symfony OWNER TO postgres;

\unrestrict sG2QAgq9dMbL9ejvd3bCykORoYNVGJGW8Rp9AJJz9zQGwjnkXuKVQf1rdWowOjJ
\connect symfony
\restrict sG2QAgq9dMbL9ejvd3bCykORoYNVGJGW8Rp9AJJz9zQGwjnkXuKVQf1rdWowOjJ

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16684)
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO admin;

--
-- TOC entry 216 (class 1259 OID 16688)
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO admin;

--
-- TOC entry 217 (class 1259 OID 16694)
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16695)
-- Name: producto; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.producto (
    id integer NOT NULL,
    nombre character varying(255) NOT NULL,
    precio double precision NOT NULL
);


ALTER TABLE public.producto OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 16698)
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3488 (class 0 OID 16684)
-- Dependencies: 215
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260122234227	2026-01-22 23:42:33	198
\.


--
-- TOC entry 3489 (class 0 OID 16688)
-- Dependencies: 216
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- TOC entry 3491 (class 0 OID 16695)
-- Dependencies: 218
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.producto (id, nombre, precio) FROM stdin;
6	mango	80
3	mamey	10
2	arrayan	10
7	sandia	90
8	guisquil	34
5	maiz	90
11	pepino	17
12	marañon	60
14	ciquitrino	120
16	Tortillas	69
17	Guanaba	56
19	Jocote	75
20	Mandarina	50
21	Uvas	30
22	Sandia	58
23	Pedro perez usado remember	60
\.


--
-- TOC entry 3499 (class 0 OID 0)
-- Dependencies: 217
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- TOC entry 3500 (class 0 OID 0)
-- Dependencies: 219
-- Name: producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.producto_id_seq', 23, true);


--
-- TOC entry 3339 (class 2606 OID 16700)
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- TOC entry 3342 (class 2606 OID 16702)
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 3344 (class 2606 OID 16704)
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- TOC entry 3340 (class 1259 OID 16705)
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


-- Completed on 2026-03-16 15:14:09 CST

--
-- PostgreSQL database dump complete
--

\unrestrict sG2QAgq9dMbL9ejvd3bCykORoYNVGJGW8Rp9AJJz9zQGwjnkXuKVQf1rdWowOjJ

-- Completed on 2026-03-16 15:14:09 CST

--
-- PostgreSQL database cluster dump complete
--

